variables:
    PLUGIN_NAME: SwagMigrationAssistant
    PLATFORM_BRANCH: 'trunk'
    DEV_IMAGE: shopware/development:8.2-composer-2

include:
    project: 'shopware/6/product/platform'
    ref: 'trunk'
    file: '.gitlab/templates/plugin.yml'

Danger:
  stage: test
  image:
    name: ghcr.io/shyim/danger-php:latest
    entrypoint: ["/bin/sh", "-c"]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  before_script: []
  script:
    - danger ci

ecs:
  stage: test
  script:
    - composer ecs

phpunit:
  script:
    - php
      -d pcov.enabled=1 -d pcov.directory=$PWD -d pcov.exclude='~(vendor|tests|node_modules)~'
      ${PROJECT_ROOT}/vendor/bin/phpunit
      --configuration phpunit.xml.dist
      --log-junit ${CI_PROJECT_DIR}/phpunit.junit.xml
      --colors=never
      --coverage-cobertura ${CI_PROJECT_DIR}/cobertura.xml
      --coverage-text #| grep -v -E '^Shopware\\|^  Methods:' # do not output covered files lines

phpstan:
  script:
    - php Test/TestBootstrap.php
    - ${PROJECT_ROOT}/vendor/bin/phpstan analyze --error-format=gitlab --no-progress | tee ${CI_PROJECT_DIR}/phpstan-report.json
